force-app/main/default/objects/Merchandise__c/Merchandise__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Merchandise Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Merchandise__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Womens</fullName>
            </value>
            <value>
                <fullName>Mens</fullName>
            </value>
            <value>
                <fullName>Kids</fullName>
            </value>
            <value>
                <fullName>Gear</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Merchandise__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Merchandise__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Merchandise__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MerchandiseController.cls
global with sharing class MerchandiseController {
    
    @AuraEnabled(cacheable=true)
    public static List<String> getCategories() {
        Schema.DescribeFieldResult result = Merchandise__c.Category__c.getDescribe();
        List<Schema.PicklistEntry> entries = result.getPicklistValues();
        List<String> values = new list <String>();
        for (Schema.PicklistEntry entry: entries) {
            values.add(entry.getValue());
        }
        return values;
    }
    
    
    public class PagedResult {
        
        @AuraEnabled
        public Integer pageSize { get;set; }
        
        @AuraEnabled
        public Integer page { get;set; }
        
        @AuraEnabled
        public Integer total { get;set; }
        
        @AuraEnabled
        public List<Merchandise__c> items { get;set; }
        
    }
    
    public class Filter {
        
        @AuraEnabled
        public String searchKey { get;set; }
        
        @AuraEnabled
        public String category { get;set; }
        
        @AuraEnabled
        public Decimal minPrice { get;set; }
        
        @AuraEnabled
        public Decimal maxPrice { get;set; }
        
    }
    
    @AuraEnabled(cacheable=true)
    public static PagedResult getMerchandise(String filters, Decimal pageSize, Decimal pageNumber) {
        Filter filter = (Filter) JSON.deserializeStrict(filters, MerchandiseController.Filter.class);
        Integer pSize = (Integer)pageSize;
        String key = '%' + filter.searchKey + '%';
        Integer offset = ((Integer)pageNumber - 1) * pSize;
        PagedResult r =  new PagedResult();
        r.pageSize = pSize;
        r.page = (Integer) pageNumber;
        r.total = [SELECT count() FROM Merchandise__c
                   WHERE name LIKE :key
                   AND Category__c like : (filter.category == '' ? '%' : filter.category)
                   AND Price__c >= :filter.minPrice AND Price__c <= :filter.maxPrice];
        r.items = [SELECT id, Name, Title__c, Description__c, Price__c, Category__c, Picture_URL__c FROM Merchandise__c
                      WHERE Name LIKE :key
                      AND Category__c like : (filter.category == '' ? '%' : filter.category)
                      AND Price__c >= :filter.minPrice AND Price__c <= :filter.maxPrice
                      LIMIT :pSize OFFSET :offset];
        return r;
    }
    
    @AuraEnabled(cacheable=true)
    public static Merchandise__c[] getAllMerchandise() {
        return [SELECT id, Name, Title__c, Description__c, Price__c, Category__c, Picture_URL__c 
                    FROM Merchandise__c];
    }
}